### ISSUE TITLE
Two weeks later, how is this helm chart holding?

### ISSUE THREAD

**Issue by mahmoudajawad** [dudeami/lemmy-chart#1]
Hello.

Thanks for your work.

You've posted this a little over two weeks and mentioned that you are using it on a test server. I also would like to run it for testing. Any updates you would like to share on your two weeks experience?

**Comment by dudeami0** [comment]
It seems to be working fine for my single user instance. Not sure if anyone else is using it, but my instance is still online with no issues after a couple upgrades.

**Comment by ndragon798** [comment]
Running it for myself and it runs fine. I have all of my storage setup in longhorn in 5 node kube cluster and pods die and come up no problems. Running external postgres using the postgres operator and that seems to have no problems.
